/* Generated by Babel */
////
//
// Operator overloading engine for TeaScript
//
////

"use strict";

TeaScript.OverloadOperator = function (Code, Escapes, operator, callback) {
  var Overloaded = "";
  for (var i = 0; i < Code.length; i++) {
    if (Escapes.map(function (S) {
      return S[0];
    }).includes(Code[i])) {} else {
      Overloaded += Code[i];
    }
  }
  return Overload;
};
